#!/usr/bin/env bash

alias zp="source /srv/zulip-py3-venv/bin/activate && cd ~/zulip"
alias zt="source ~/zulip-terminal-venv/bin/activate && cd ~/zulip-terminal"
alias zl="source ~/zulint_env/bin/activate && cd ~/zulint"

alias zssh="mosh  zulipdev@amanagr.zulipdev.org"
alias run_dev="export EXTERNAL_HOST=165.22.37.10:9991 && ~/zulip/tools/run-dev.py --interface=''" 
