#!/usr/bin/env bash

alias zp="source /srv/zulip-py3-venv/bin/activate && cd ~/zulip"
alias zt="source ~/zulip-terminal-venv/bin/activate && cd ~/zulip-terminal"
alias zl="source ~/zulint_env/bin/activate && cd ~/zulint"


alias remote_start="gcloud compute instances start instance-1 --zone asia-south1-c"
alias ssh_remote=" gcloud compute ssh instance-1 --zone asia-south1-c"
alias remote_stop="gcloud compute instances stop instance-1 --zone asia-south1-c"

alias zssh="mosh  zulipdev@amanagr.zulipdev.org"
alias run_dev="export EXTERNAL_HOST=165.22.37.10:9991 && ~/zulip/tools/run-dev.py --interface=''" 
