#!/usr/bin/env bash


sudo apt-get install zsh curl git

# Install OH-MY-ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

source ~/.zshrc

PLDIR="$ZSH_CUSTOM/themes/powerlevel10k"
if [ -d "$PLDIR" ]; then rm -rf "$PLDIR"; fi


# Install powerline10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git  "$PLDIR"

echo ZSH_THEME=powerlevel10k/powerlevel10k >> ~/.zshrc
echo [[ ! -f ~/setup_terminal/custom_commands ]] || source  ~/setup_terminal/custom_commands >> ~/.zshrc

